let config_language = new Map([
            ['flagsrc', new Map([ ['en','flags/english.png'],['fr','flags/francais.png'],['es','flags/espanol.png'],['de','flags/deutsch.png'] ])],
            ['buttons', new Map([ ['en',['MCQ','Normal','Time trial','PLAY','BACK','SKIP','NEXT']],['fr',['QCM','Normal','Contre-la-montre','JOUER','RETOUR','PASSER','SUIVANT']],['es',['Multiopción','Normal','Contrarreloj','JUGAR','REGRESO','SALTAR','PROXIMA']],['de',['MultipleChoice','Normal','Zeitfahren','SPIELEN','RUCKKEHR','UBERSPRINGEN','NACHSTE']] ])],
            ['infobulle', new Map([ 
                ['en',["• 20 random movie soundtrack 30s clips\n• 4 answers proposed, only 1 correct\n• 45s max per question\n• 100pts per correct answer", "• 10 random movie soundtrack 30s clips\n• answer to write in the autocomplete field\n• 1min max per question\n• 25 to 100pts per correct answer depending on the time used", "• Unlimited number of soundtrack clips\n• 5min granted\n• 100pts per correct answer, -25pts per wrong answer"]],
                ['fr',["• 20 extraits de 30s de bande sonore de films aléatoires\n• 4 réponses proposées, 1 seule correcte\n• 45s max par question\n• 100pts par bonne réponse", "• 10 extraits de 30s de bande sonore de films aléatoires\n• réponse à écrire dans le champ de saisie semi-automatique\n• 1min max par question\n• 25 à 100pts par bonne réponse selon le temps utilisé", "• Nombre d'extraits de bande sonore illimité\n• 5min accordée\n• 100pts par bonne réponse, -25pts par mauvaise réponse"]],
                ['es',["• 20 clips aleatorios de bandas sonoras de películas de 30s\n• 4 respuestas propuestas, solo 1 correcta\n• 45s como máximo por pregunta\n• 100pts por respuesta correcta", "• 10 clips aleatorios de bandas sonoras de películas de 30s\n• respuesta para escribir en el campo de autocompletar\n• 1min como máximo por pregunta\n• 25 a 100pts por respuesta correcta dependiendo del tiempo empleado", "• Número ilimitado de clips de bandas sonoras\n• 5min concedidos\n• 100pts por respuesta correcta, -25pts por respuesta incorrecta"]],
                ['de',["• 20 zufällige 30-Sekunden-Film-Soundtrack-Clips\n• 4 Antworten vorgeschlagen, nur 1 richtig\n• 45 Sekunden max. pro Frage\n• 100 Punkte pro richtige Antwort", "• 10 zufällige 30-Sekunden-Film-Soundtrack-Clips\n• Antwort in das Autocomplete-Feld schreiben\n• 1min max. pro Frage\n• 25 bis 100 Punkte pro richtiger Antwort je nach Zeitaufwand", "• Unbegrenzte Anzahl von Soundtrack-Clips\n• 5min gewährt\n• 100 Punkte pro richtige Antwort, -25 Punkte pro falsche Antwort"]] 
            ])],
            ['placeholder', new Map([ ['en','What movie is this music from?'],['fr','De quel film provient cette musique ?'],['es','¿De qué película es esta música?'],['de','Aus welchem ​​Film stammt diese Musik?'] ])],
            ['ytb', new Map([ ['en','Listen more on YouTube'],['fr',"Ecouter plus sur YouTube"],['es','Escucha más en YouTube'],['de','Hören Sie mehr auf YouTube'] ])],
            ['confirm', new Map([ ['en','Warning!\nYou will not be able to resume the game in progress.\nWould you like to return to the homepage?'],['fr',"Attention !\nVous ne pourrez pas revenir sur la partie en cours.\nSouhaitez-vous revenir à l'accueil ?"],['es','Atención!\nNo podrás reanudar el juego en curso.\n¿Quieres volver a la página de inicio?'],['de','Warnung !\nSie können das laufende Spiel nicht fortsetzen.\nMöchten Sie zur Startseite zurückkehren?'] ])],
        ]);